services:
  - type: web
    name: budge-it
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.7.18
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0 