services:
  - type: web
    name: budget-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --timeout 120 --workers 1 --worker-class sync --max-requests 100 --max-requests-jitter 10 --keep-alive 2 --preload --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FLASK_ENV
        value: production
      - key: SQLALCHEMY_ENGINE_OPTIONS
        value: '{"pool_size": 2, "pool_recycle": 1800, "pool_pre_ping": true, "max_overflow": 3, "pool_timeout": 20}' 