services:
  - type: web
    name: budget-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FLASK_ENV
        value: production
      - key: SQLALCHEMY_ENGINE_OPTIONS
        value: '{"pool_size": 1, "pool_recycle": 1800, "pool_pre_ping": true, "max_overflow": 1, "pool_timeout": 10}' 