services:
  - type: web
    name: budge-it
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.18
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py 