# Nhost deployment configuration for Budge-IT Flask app
services:
  - name: budge-it
    type: web
    image: python:3.11.10-slim
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
      - ./static:/app/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  - name: postgres
    type: postgres
    image: postgres:15
    environment:
      - POSTGRES_DB=budge_it
      - POSTGRES_USER=nhost
      - POSTGRES_PASSWORD=nhost
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: 